### ISSUE TITLE
编译不过，gradle文件也没传上来

### ISSUE THREAD

**Issue by davinliuda** [AchillesLzg/jianshu-neteasedisc#1]

**Comment by BurnieLiu** [comment]
作者上传的是单独的module 不是整个project 所以自己建个project  import module就好了

**Comment by Sum41forever** [comment]
自己建一个project  把这个module放到APP里面去就行了。
![图片](https://cloud.githubusercontent.com/assets/18468976/22721789/ccc57426-eded-11e6-9463-8b04d588eada.png)
